#!/bin/bash
#
# Repeated executes a pre-compiled correct solution to problem, with optional
# input from stdin.
#
# Args:
#   suite-file: path to file containing test filename stems (delimiter: spaces) 
#   program: path to program to test
#
# Raises:
#   If incorrect number of command line arguments are supplied: Will EXIT w/
#   non-zero status, and print error msg to sterr.
#
# Example:
#   PS1$ ./produceOutputs suite.txt ./myprogram
#

readonly INCORRECT_NUM_ARGS_STATUS=7
readonly INCORRECT_NUM_ARGS_MSG="Incorrect number of arguments supplied.\
                                 Please supply 2 arguments: suite-file, program."

# Input validation 
suite_file=$1
program=$2

if [[ $# != 2 ]]; then 
    echo $INCORRECT_NUM_ARGS_MSG >&2
    EXIT $INCORRECT_NUM_ARGS_STATUS
fi

# Run program for every test 
test_files=$(cat $suite_file)

for file in $test_files; do 
    echo "Running $file"
    arg_file="${file}.args"
    out_file="${file}.out"
    in_file="${file}.in"

    args=$""
    if [[ -f $arg_file ]]; then
        args=$(cat $arg_file)
    fi

    if [[ -f $in_file ]]; then
        "$program" $args < "$in_file" > "$out_file"
    else
        "$program" $args > "$out_file"
    fi

done 
